name: "test"
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

permissions: {}

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
    - run: |
        yarn
        yarn build:pack
    - uses: ./
